### ISSUE TITLE
elastix resampled image from transformix and ItkTransform resampled image produce different results for same transformations  

### ISSUE THREAD

**Issue by NHPatterson** [InsightSoftwareConsortium/ITKElastix#110]
Hi all, specifically @ViktorvdValk @N-Dekker 

I've been monitoring a bit the GitHub issues and upcoming PRs for `ITKElastix` and `elastix` itself and thought it was timely to bring this issue up considering the direction things are going for interoperability between elastix and ITK transforms. I wasn't sure exactly where to file this so I will put it here and have tagged who I think would be interested.

**Related issues:**
#79 
elastix:
https://github.com/SuperElastix/elastix/pull/387

## Background
I am registering some 2D microscopy images and having great results with `elastix`, however, I'd like to use a bit more of ITK for managing point set transformations and composing long and complex sequences of transforms. However, in my initial tests I've discovered that the resampling in ITK and elastix can produce different images with spatial shifts that could affect point set and image transformations.

## Reproducible example & data

Here is a full example with data (data link: https://drive.google.com/file/d/1-bUfi69YmBVGFPzX4XRTPPCkIja9Qur8/view?usp=sharing, sorry it is microscopy so rather large 1.1 GB, includes both the moving image, and ITK and elastix transformed images) using SimpleITK but I think it would apply to ITK or elastix implementation one uses. Apologies for the length, I wanted everything to be as clear as possible.
```python
import numpy as np
import SimpleITK as sitk
import napari


def elx_to_itk_euler2d(transform_data):
    t_params = np.asarray(transform_data["TransformParameters"]).astype(np.float)
    t_center = np.asarray(transform_data["CenterOfRotationPoint"]).astype(np.float)

    theta = t_params[0]
    c, s = np.cos(theta), np.sin(theta)
    rotmat = np.array(((c, -s), (s, c)))

    affine = sitk.AffineTransform(2)
    affine.SetTranslation(t_params[-2:].tolist())
    affine.SetMatrix(rotmat.flatten().tolist())
    affine.SetCenter(t_center.tolist())
    return affine


def elx_to_itk_affine2d(transform_data):
    t_params = np.asarray(transform_data["TransformParameters"]).astype(np.float)
    t_center = np.asarray(transform_data["CenterOfRotationPoint"]).astype(np.float)

    affine = sitk.AffineTransform(2)
    affine.SetTranslation(t_params[-2:].tolist())
    affine.SetMatrix(t_params[:4].flatten().tolist())
    affine.SetCenter(t_center.tolist())
    return affine


# read elastix parameter files
euler_pmap = sitk.ReadParameterFile("./example-data/TransformParameters.0.txt")
affine_pmap = sitk.ReadParameterFile("./example-data/TransformParameters.1.txt")

# read moving image and set spacing
moving_im = sitk.ReadImage("./example-data/moving_image.tif")
moving_im.SetSpacing((0.65, 0.65))

# set up fixed image from last transform in sequence
size_out = np.asarray(affine_pmap["Size"]).astype(np.int)
spacing_out = np.asarray(affine_pmap["Spacing"]).astype(np.float)
# direction and origin are default
fixed_im = sitk.Image(size_out.tolist(), sitk.sitkUInt16)
fixed_im.SetSpacing(spacing_out.tolist())

# convert elastix transform parameter maps to ITK representations
itk_euler = elx_to_itk_euler2d(euler_pmap)
itk_affine = elx_to_itk_affine2d(affine_pmap)

# compose sequential transforms
compos_tform = sitk.Transform(2, sitk.sitkComposite)
compos_tform.AddTransform(itk_euler)
compos_tform.AddTransform(itk_affine)

# apply transform
itk_resampled_im = sitk.Resample(
    moving_im, fixed_im, compos_tform, sitk.sitkNearestNeighbor, 0
)

# load elastix resampled image
elx_resampled_im = sitk.ReadImage("./example-data/elx_resampled_image.tif")

# optionally read the ITK resampled image from disk rather than computing it
# itk_resampled_im = sitk.ReadImage("./example-data/itk_resampled_image.tif")

# visualize with napari
with napari.gui_qt():
    viewer = napari.Viewer()
    viewer.add_image(
        sitk.GetArrayFromImage(itk_resampled_im),
        name="itk resampled",
        contrast_limits=[0, 5000],
        colormap="red",
        blending="additive"

    )
    viewer.add_image(
        sitk.GetArrayFromImage(elx_resampled_im),
        name="elx resampled",
        contrast_limits=[0, 5000],
        colormap="green",
        blending="additive"
    )
```
## Results
Here are the results with red-green (elastix, itk) additive color blending of the different resamplings:
low-res is ok
![image](https://user-images.githubusercontent.com/17855764/109589156-869a2500-7acf-11eb-936c-ae45c8d74972.png)

high-res shows some issues, a small positive shift of itk image 
![image](https://user-images.githubusercontent.com/17855764/109589266-ad585b80-7acf-11eb-91d1-45f3ee9ead7b.png)

I've also looking at corresponding areas between the original moving image and the different resamplings and elastix's resampled image has higher fidelity to the original pixel intensities and shapes and is a closer alignment with the fixed image.

Not sure what is the cause of this. Other things I've explored producing the same result:
* downsampling of the image 
* precision of numbers in `TransformParameters`
* sequence transformation rather than ITK composition transform, i.e., transform with euler -> interpolate -> affine -> interpolate
 
Sorry for the long issue.. hope it is clear.

**Comment by ViktorvdValk** [comment]
Can you confirm that your rotation matrix calculation is correct? Could you try setting the rotation matrix for you affine transform with the inverse of the matrix you calculate here?

**Comment by NHPatterson** [comment]
@ViktorvdValk 

I'm quite certain the rotation matrix computation is correct and probably doesn't matter much in this case. Using `skimage`:

```python
from skimage.transform import AffineTransform

affmat = AffineTransform(
    rotation=np.rad2deg(float(euler_pmap["TransformParameters"][0]))
)
print(affmat.params[:2, :2].flatten())

[ 1.,-0.0000573,0.0000573,1.]

```

ITK:
```python
print(itk_euler.GetMatrix())
(0.9999999999995, -9.999999999998333e-07, 9.999999999998333e-07, 0.9999999999995)
```


For the rotation matrix, the rotation of the euler transform is very very small, below is the condensed transform from the text file. 
```
(Transform "EulerTransform")
(NumberOfParameters 3)
(TransformParameters 0.000001 -219.341340 -62.119842)
(Size 14923 19969)
(Index 0 0)
(Spacing 0.6500000000 0.6500000000)
(Origin 0.0000000000 0.0000000000)
(Direction 1.0000000000 0.0000000000 0.0000000000 1.0000000000)
(CenterOfRotationPoint 4849.6500000000 6489.6000000000)
```
Which is nearly just the identity (I also tried just setting the matrix to (1,0,0,1) and got the exact same result I showed in the first post. I do wonder if these very small numbers are having an influence somewhere.


Here is the result using the identity for matrix transform (see below for all the different inversions.
```python
compos_tform = sitk.Transform(2, sitk.sitkComposite)
itk_euler.SetMatrix((1.,0.,0.,1.))
compos_tform.AddTransform(itk_euler)
compos_tform.AddTransform(itk_affine)
```
![image](https://user-images.githubusercontent.com/17855764/109664531-d3fbae00-7b32-11eb-9768-c77ac2698373.png)


I have tried using the inverse of both transforms in combination or using the inverse of one and the other.

dropping in:
 ```python
# compose sequential transforms
compos_tform = sitk.Transform(2, sitk.sitkComposite)
compos_tform.AddTransform(itk_euler)
compos_tform.AddTransform(itk_affine.GetInverse())
```
Result:
![image](https://user-images.githubusercontent.com/17855764/109663838-25576d80-7b32-11eb-8bc0-f223f558f3ba.png)
high mag:
![image](https://user-images.githubusercontent.com/17855764/109663906-3902d400-7b32-11eb-93c8-f8970717224b.png)

dropping in:
 ```python
# compose sequential transforms
compos_tform = sitk.Transform(2, sitk.sitkComposite)
compos_tform.AddTransform(itk_euler.GetInverse())
compos_tform.AddTransform(itk_affine)
```
Result:
![image](https://user-images.githubusercontent.com/17855764/109663618-f04b1b00-7b31-11eb-8cf0-0dc1d7ea6829.png)


dropping in:
 ```python
# compose sequential transforms
compos_tform = sitk.Transform(2, sitk.sitkComposite)
compos_tform.AddTransform(itk_euler.GetInverse())
compos_tform.AddTransform(itk_affine.GetInverse())
```
Result:
![image](https://user-images.githubusercontent.com/17855764/109664043-5df74700-7b32-11eb-879c-610ffd9caee4.png)

Another thing I tried was casting the image to `float32 `prior to transformation (as `itk-elastix` requires) but I got the same result.

**Comment by ViktorvdValk** [comment]
Hi @NHPatterson,
What I meant was the inverse of the rotation matrix, so the inverse of the rotmat variable you defined. So than you elx_to_itk_euler2d function would look like:
```
def elx_to_itk_euler2d(transform_data):
    t_params = np.asarray(transform_data["TransformParameters"]).astype(np.float)
    t_center = np.asarray(transform_data["CenterOfRotationPoint"]).astype(np.float)

    theta = t_params[0]
    c, s = np.cos(theta), np.sin(theta)
    rotmat = np.array(((c, -s), (s, c))).inv

    affine = sitk.AffineTransform(2)
    affine.SetTranslation(t_params[-2:].tolist())
    affine.SetMatrix(rotmat.flatten().tolist())
    affine.SetCenter(t_center.tolist())
    return affine
```

But given that the rotation is very small, this might not matter that much.
The reason for this, is that different conventions for the calculation of the rotation matrix exist and I'm not sure if the convention that SimpleITK's GetMatrix function uses is the same as the one in your elx_to_itk_euler2d function.

**Comment by NHPatterson** [comment]
Ah yes, I see...

Ok here is this version using to invert the rotation matrix.
```python

def elx_to_itk_euler2d(transform_data):
    t_params = np.asarray(transform_data["TransformParameters"]).astype(np.float)
    t_center = np.asarray(transform_data["CenterOfRotationPoint"]).astype(np.float)

    theta = t_params[0]
    c, s = np.cos(theta), np.sin(theta)
    rotmat = np.array(((c, -s), (s, c)))
    rotmat = np.linalg.inv(rotmat)

    affine = sitk.AffineTransform(2)
    affine.SetTranslation(t_params[-2:].tolist())
    affine.SetMatrix(rotmat.flatten().tolist())
    affine.SetCenter(t_center.tolist())
    return affine
```

![image](https://user-images.githubusercontent.com/17855764/109671194-7cad0c00-7b39-11eb-84e5-c7c11adffc5c.png)

**Comment by ViktorvdValk** [comment]
Ah oke, so still not the same.

I'm not really familiar with SimpleITK, but why does this function need 2 images:
```
# apply transform
itk_resampled_im = sitk.Resample(
    moving_im, fixed_im, compos_tform, sitk.sitkNearestNeighbor, 0
)
```
if it's applying a transform on 1 image?
And why would you set a NearestNeighbor interpolator to 0?

**Comment by NHPatterson** [comment]
The second image defines the output size, spacing & direction, see [docs](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1ResampleImageFilter.html).

Relevant section below, bolding explains why the fixed is set:
> Output information (spacing, size and direction) for the output image should be set. This information has the normal defaults of unit spacing, zero origin and identity direction. **Optionally, the output information can be obtained from a reference image.** If the reference image is provided and UseReferenceImage is On, then the spacing, origin and direction of the reference image will be used.

So in the case when the functional (`sitk.Resample`) of the `ResampleImageFilter` is called, I think the image is required, but you could also just set these using `.SetOutputSpacing(...)`, `.SetOutputSize(...)`, etc in `ResampleImageFilter`.

The `0` is the default pixel value for those pixels outside of the image domain. The `sitk.sitkNearestNeighbor` is an enumeration defining the interpolation settings for the resampling.

**Comment by NHPatterson** [comment]
For what it's worth, the issue persists if I use an linear interpolator for the resampling:

```python
itk_resampled_im = sitk.Resample(
    moving_im, fixed_im, compos_tform, sitk.sitkLinear, 0
)
```
I also used `FinalLinearInterpolator` for the `elastix` transformed image.
![image](https://user-images.githubusercontent.com/17855764/109677149-01e6ef80-7b3f-11eb-8fda-d93653c1ec2b.png)

**Comment by thewtex** [comment]
@NHPatterson thanks for the detailed report. :1st_place_medal: 

Are you using the latest version of the `itk-elastix` package? @N-Dekker recently improved elastix parameter serialization precision with plain text serialization. This may help.

Ulimately, it would be nice to obtain `itk.Transform` object in memory as the output of elastix and apply them with other filters.

@mstaring @stefanklein

**Comment by NHPatterson** [comment]
@thewtex I actually developed these registrations using a older version of `SimpleElastix` that I compiled probably 7-8 months ago so it definitely has older versions of `SimpleITK` & `elastix`. I will reproduce the registration using `itk-elastix` in a fresh environment in short order and see if that solves this problem. Thanks

**Comment by NHPatterson** [comment]
I did update to the last version of everything and now the parameters are serialized to a more precise number, but the problem persists exactly as before. 

I think the issue is in the compositing of transforms. In the registration I perform a euler transform then follow with an affine transform. I tried running each individually as a single transformation and in both the cases the resampling by `ITK` and `elastix` are perfectly matched.

**Affine example**
![image](https://user-images.githubusercontent.com/17855764/109996924-4c01d980-7cd5-11eb-87da-b565c63540d0.png)

I also tried an iterative approach. Running the two alignments separately (register, take registered image output, register this output again to fixed, see code below) and then composing the transforms through `ITK`.
```python

parameter_object_euler = itk.ParameterObject.New()
parameter_object_euler.AddParameterMap(euler_params)
result_image_euler, result_transform_parameters_euler = itk.elastix_registration_method(
    fixed_im, moving_im,
    parameter_object=parameter_object_euler,
    log_to_console=True)

parameter_object_affine = itk.ParameterObject.New()
parameter_object_affine.AddParameterMap(affine_params)
result_image_affine, result_transform_parameters_affine = itk.elastix_registration_method(
    fixed_im, result_image_euler,
    parameter_object=parameter_object_affine,
    log_to_console=True)
``` 
The error is now much smaller but there is still some error present but it's much smaller.
![image](https://user-images.githubusercontent.com/17855764/110000320-c4b66500-7cd8-11eb-9757-ef613ea159fb.png)

I also tried concatenating the `elastix` transforms through `transformix` like so:
```python
transformix_object = itk.TransformixFilter.New(moving_im)
tfx_params = itk.ParameterObject.New()
tfx_params.AddParameterMap(result_transform_parameters_euler.GetParameterMap(0))
tfx_params.AddParameterMap(result_transform_parameters_affine.GetParameterMap(0))
transformix_object.SetTransformParameterObject(tfx_params)

transformix_object.UpdateLargestPossibleRegion()
result_image_transformix = transformix_object.GetOutput()
```
but this image is significantly wrong result which seems like an `elastix` error, it works when one does `transformix` twice.

It seems there is a difference in how

**Comment by thewtex** [comment]
@NHPatterson thanks for the detailed follow-up and experiments.

I created the following example, aimed at your use case, euler followed by affine: https://github.com/InsightSoftwareConsortium/ITKElastix/pull/111. This generates in-memory `itk.Transform`'s from the `ParameterMap`. Please try it and let us know how it goes.

@N-Dekker I noticed there were not too many units of precision in the `ParameterMap` `TransformParameters`:

```
>>> print(result_transform_parameters)

ParameterObject (0x564f34e84590)
  RTTI typeinfo:   elastix::ParameterObject
  Reference Count: 1
  Modified Time: 68200
  Debug: Off
  Object Name: 
  Observers: 
    none
ParameterMap 0: 
  (CenterOfRotationPoint 127.5 127.5)
  (CompressResultImage "false")
  (DefaultPixelValue 0)
  (Direction 1 0 0 1)
  (FinalBSplineInterpolationOrder 3)
  (FixedImageDimension 2)
  (FixedInternalImagePixelType "float")
  (HowToCombineTransforms "Compose")
  (Index 0 0)
  (InitialTransformParametersFileName "NoInitialTransform")
  (MovingImageDimension 2)
  (MovingInternalImagePixelType "float")
  (NumberOfParameters 3)
  (Origin 0 0)
  (ResampleInterpolator "FinalBSplineInterpolator")
  (Resampler "DefaultResampler")
  (ResultImageFormat "nii")
  (ResultImagePixelType "float")
  (Size 256 256)
  (Spacing 1 1)
  (Transform "EulerTransform")
  (TransformParameters -0.00102041 -0.954586 -0.0057544)
  (UseDirectionCosines "true")
ParameterMap 1: 
  (CenterOfRotationPoint 126.545 127.494)
  (CompressResultImage "false")
  (DefaultPixelValue 0)
  (Direction 1 0 0 1)
  (FinalBSplineInterpolationOrder 3)
  (FixedImageDimension 2)
  (FixedInternalImagePixelType "float")
  (HowToCombineTransforms "Compose")
  (Index 0 0)
  (InitialTransformParametersFileName 0)
  (MovingImageDimension 2)
  (MovingInternalImagePixelType "float")
  (NumberOfParameters 6)
  (Origin 0 0)
  (ResampleInterpolator "FinalBSplineInterpolator")
  (Resampler "DefaultResampler")
  (ResultImageFormat "nii")
  (ResultImagePixelType "float")
  (Size 256 256)
  (Spacing 1 1)
  (Transform "AffineTransform")
  (TransformParameters 0.998661 -0.000780346 -0.0108144 1.00082 -0.195763 -0.132443)
  (UseDirectionCosines "true")
```

Is Google Double Conversion also used to generate the in-memory `TransformParameters` here?

@mstaring @stefanklein The *Convert the Elastix ParameterMap to ITK Transform's.* cell is a bit cumbersome. @ViktorvdValk perhaps create a few Python functions, e.g. `parameter_map_to_transform`, `parameter_object_to_transform_list`, to provide this functionality, then we start adding support for more transform types? Or, @N-Dekker maybe create an `itk::ParameterMapToTransform` class, inheriting from `itk::ProcessObject` that we wrap? As a next step? We would have more control over the string -> float conversion in that case. With this functionality, we can also generate ITK HDF5 transforms from Elastix with `itk.transformread`, `itk.transformwrite`.

**Comment by NHPatterson** [comment]
@thewtex Thanks for the follow up again. I tried this version and I get the same result as previous:

![image](https://user-images.githubusercontent.com/17855764/110564132-fa60b100-8111-11eb-8033-3f21ec47dbc9.png)

In this case the error looks to be about 2 pixels. I think the precision issue makes sense in my case as the rotation is very small.
```C
ParameterObject (000001E019F27C10)
  RTTI typeinfo:   class elastix::ParameterObject
  Reference Count: 1
  Modified Time: 387077
  Debug: Off
  Object Name: 
  Observers: 
    none
ParameterMap 0: 
  (CenterOfRotationPoint 4849.65 6489.6)
  (CompressResultImage "true")
  (DefaultPixelValue 0)
  (Direction 1 0 0 1)
  (FixedImageDimension 2)
  (FixedInternalImagePixelType "float")
  (HowToCombineTransforms "Compose")
  (Index 0 0)
  (InitialTransformParametersFileName "NoInitialTransform")
  (MovingImageDimension 2)
  (MovingInternalImagePixelType "float")
  (NumberOfParameters 3)
  (Origin 0 0)
  (ResampleInterpolator "FinalNearestNeighborInterpolator")
  (Resampler "DefaultResampler")
  (ResultImageFormat "mha")
  (ResultImagePixelType "float")
  (Size 14923 19969)
  (Spacing 0.65 0.65)
  (Transform "EulerTransform")
  (TransformParameters -0.000191446 -217.238 -57.3014)
  (UseDirectionCosines "true")
ParameterMap 1: 
  (CenterOfRotationPoint 4632.41 6432.3)
  (CompressResultImage "true")
  (DefaultPixelValue 0)
  (Direction 1 0 0 1)
  (FixedImageDimension 2)
  (FixedInternalImagePixelType "float")
  (HowToCombineTransforms "Compose")
  (Index 0 0)
  (InitialTransformParametersFileName 0)
  (MovingImageDimension 2)
  (MovingInternalImagePixelType "float")
  (NumberOfParameters 6)
  (Origin 0 0)
  (ResampleInterpolator "FinalNearestNeighborInterpolator")
  (Resampler "DefaultResampler")
  (ResultImageFormat "mha")
  (ResultImagePixelType "float")
  (Size 14923 19969)
  (Spacing 0.65 0.65)
  (Transform "AffineTransform")
  (TransformParameters 0.994175 0.000809821 0.00308613 0.994757 -3.4608 -6.83434)
  (UseDirectionCosines "true")
```

Could thee also be something different with the `CenterOfRotationPoint`? In the above case it is:
`(4849.650000000001, 6489.6)` for euler
`(4632.412005843545, 6432.298641807473)` for affine

**Comment by mstaring** [comment]
Could you check the following two things?

- reverse the order of the itk composite transform, so first T2 then T1 instead of the other way around? In elastix/transformix we do T2(T1(x)), perhaps the itk::composite transform does it the other way around T1(T2(x))?
- check in the code if function composition is used T2(T1(x)) or function addition T1(x) + T2(x). In elastix we support both, but composition is the default. I am not sure what the itk::composite transform does.

**Comment by NHPatterson** [comment]
@mstaring Reverse the order seems to have worked! I'm really surprised I didn't try this, it seems so obvious. It was also important to have the higher precision numbers as I have tested on an older version of `ITKElastix` as well. 

@thewtex This will affect the resampling notebook you have uploaded. Another note there: the default interpolator is Linear (I  believe) for itk resampling whereas the elastix method is a "FinalBSplineInterpolator" with order = 3. 

```python
# switch ordering
composite_transform = itk.CompositeTransform[itk.D, dimension].New()
composite_transform.AddTransform(affine_transform)
composite_transform.AddTransform(euler_transform)

# set interpolation
interpolator = itk.BSplineInterpolateImageFunction.New(moving_image)
interpolator.SetSplineOrder(3)

# add interpolation kwarg
result_image_itk = itk.resample_image_filter(moving_image,
                                             transform=composite_transform,
                                             use_reference_image=True,
                                             reference_image=fixed_image,
                                             interpolator=interpolator)

```
