### ISSUE TITLE
registration with mask does not work

### ISSUE THREAD

**Issue by jslalu** [InsightSoftwareConsortium/ITKElastix#127]
I tried to use a binary mask as the fixed mask to guide the registration, but the log said fMask was unspecified. What Should I do to make the mask work?

**Comment by ViktorvdValk** [comment]
Did you have a look at the example notebooks yet?
In case of masks, [example 3](https://github.com/InsightSoftwareConsortium/ITKElastix/blob/master/examples/ITK_Example03_Masked_3D_Registration.ipynb) might be helpful.

**Comment by jslalu** [comment]
> Did you have a look at the example notebooks yet?
> In case of masks, [example 3](https://github.com/InsightSoftwareConsortium/ITKElastix/blob/master/examples/ITK_Example03_Masked_3D_Registration.ipynb) might be helpful.

I did refer to example 3, but the log still said both fMask and mMask were unspecified. Here's my code.

    elastix_object = itk.ElastixRegistrationMethod.New(fixed_image, moving_image)
    elastix_object.SetFixedMask(mask)
    elastix_object.SetMovingMask(mask)
    elastix_object.SetParameterObject(parameter_object)
    elastix_object.SetLogToConsole(True)
    elastix_object.UpdateLargestPossibleRegion()
    result_image = elastix_object.GetOutput()
    result_transform_parameters = elastix_object.GetTransformParameterObject()

**Comment by ViktorvdValk** [comment]
Can you also show the part of the code that loads the mask?
And why would you want to use the same mask for both the fixed and the moving mask?

**Comment by ntatsisk** [comment]
The empty BufferedRegion seems to be caused by not setting `WriteResultImage` to `True` (as reported in https://github.com/InsightSoftwareConsortium/ITKElastix/issues/157).

However, I am not sure if the masks are _not_ read. Indeed, the [log](https://github.com/InsightSoftwareConsortium/ITKElastix/files/11442175/log.log) indicates:

> 
> ELASTIX version: 5.1.0
> Command line options from ElastixBase:
> -fMask    unspecified, so no fixed mask used
> -mMask    unspecified, so no moving mask used
> 

but later it also reports:

> Setting the fixed masks took: 0 ms.
> Setting the moving masks took: 1 ms.

So, I assume the masks are being used.. cc. @N-Dekker
