### ISSUE TITLE
Transforming the Transform Parameters to a homogeneous transformation matrix 

### ISSUE THREAD

**Issue by Yggdrasil1** [InsightSoftwareConsortium/ITKElastix#134]
I would like a way of outputting the transformation parameters as a single transformation matrix.
As an intermediate solution, a clear explanation on how to use the information given in the Transform Parameters to achieve the same result as the output of the registration. 

Currently I am using the Center of Rotation (z, y, x) and the 6 Transform values (z_rot, y_rot, x_rot, z_trans, y_trans, x_trans)
to create this matrix myself, but there are slight differences in the result of the image transformed with my matrix and the direct result of the registration. What is the order of the rotations? Is the description of the 6 Transform values even correct?

------------------------------------------

Edit:

After a week  of trying and just 4 hours after typing this issue I finally figured out what elastix was doing:

CenterOfRotation (z, y, x)
TransformValues (**-** z_rot, **-** y_rot, **-** x_rot, z_trans, y_trans, x_trans)

To get the Homogeneous Transformation Matrix you need to shift the volume to the center (0,0,0) using the 
CenterOfRotation.

```
CoR_mat = np.array([[1,0,0, -x ],
         [0,1,0, -y ],
         [0,0,1, -z ], 
         [0,0,0,1]])

```
(np being numpy)
Then rotate the volume and shift it back to its original position. Remember that you need the value from the parameter file **multiplied with -1**.
```
x_rot = np.array([[1, 0, 0, 0],
                      [0, math.cos(x_rot), -math.sin(x_rot), 0],
                      [0, math.sin(x_rot), math.cos(x_rot), 0], 
                      [0, 0, 0, 1]])
    
y_rot = np.array([[math.cos(y_rot), 0, math.sin(y_rot), 0],
                      [0, 1, 0, 0],
                      [-math.sin(y_rot), 0, math.cos(y_rot), 0],
                      [0, 0, 0, 1]])
    
z_rot = np.array([[math.cos(z_rot), -math.sin(z_rot), 0, 0],
                      [math.sin(z_rot), math.cos(z_rot), 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])
    
rotation_mat =  z_rot @ y_rot @ x_rot

neg_CoR_mat = np.array([[1,0,0, x * scale],
                                 [0,1,0, y * scale],
                                 [0,0,1, z * scale], 
                                 [0,0,0,1]])

```
At last just apply the translation from the parameter file and multiply it all together:

```
translation_m = np.array([[1,0,0, x_trans],
                                 [0,1,0, y_trans],
                                 [0,0,1, z_trans], 
                                 [0,0,0,1]])

HMT = translation_m @ neg_CoR_mat  @ rotation_mat @ CoR_mat 

```
BUT!: This is a Pull transformation, things like scipy take this matrix to apply it to a volume, mathematically you would need to 
inverse it to apply it to a vector to get the transformed vector you wanted. 

This gave me a headache...

**Comment by dzenanz** [comment]
ITK's transforms transform points from moving frame of reference (usually the moving image of the registration) to the fixed frame of reference. This is to ensure that moving image can be fully resampled, even if the transform is not invertible. However most humans (myself included) think of transforms as going from fixed image to the moving image.

There was recently a discussion about Elastix composing the transforms in opposite order from ITK, in case you run into that too.
