### ISSUE TITLE
Installation not working on M1 Macs

### ISSUE THREAD

**Issue by AdrianButnar** [InsightSoftwareConsortium/ITKElastix#136]
I have tried installing using `pip install itk-elastix` on my M1 Macbook, but I get the error:

`ERROR: Could not find a version that satisfies the requirement itk-elastix (from versions: none)
ERROR: No matching distribution found for itk-elastix`

I have tried with Python 3.7, 3.8 and 3.9 with no success. I have also tried compiling from source with no success. 
My experience with compiling these sort of packages is minimal? Could you provide some help?

**Comment by NHPatterson** [comment]
I am also having an issue on M1. I can install the x64_x86 macos package, but I get the following error on initialization of itk-elastix.

```python
import itk
import numpy as np

im = np.random.randint(0,255,(1024,1024),dtype=np.uint8)

# works!
itk.GetImageFromArray(im)

# elx stuff below doesn't work
itk.ElastixRegistrationMethod.New(im, im)

itk.elastix_registration_method(im,im)
```

```python
Traceback (most recent call last):
  File "/Users/nhp/opt/miniconda3/envs/wsireg-dev/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-4b8bda8d082a>", line 1, in <module>
    itk.elastix_registration_method(im,im)
  File "/Users/nhp/opt/miniconda3/envs/wsireg-dev/lib/python3.8/site-packages/itk_core-5.3rc2.post1-py3.8-macosx-10.9-x86_64.egg/itk/support/lazy.py", line 130, in __getattribute__
    value = types.ModuleType.__getattribute__(self, attr)
AttributeError: module 'itk' has no attribute 'elastix_registration_method'

```

**Comment by williamc96** [comment]
I'm having this issue too. Is there any plans to continue supporting this for new mac models or are we out of luck? It does look like someone else had success with the original [SimpleElastix](https://github.com/SuperElastix/SimpleElastix/issues/413).

**Comment by thewtex** [comment]
Experimental `itk-elastix` 0.14.2 binary wheels for M1 / arm mac's have been uploaded to PyPI for 3.9, 3.10 -- please give them a try and let us know how it goes!

**Comment by williamc96** [comment]
Looks like it's working! Thanks for the quick fix/response!
