### ISSUE TITLE
The result is the same with and without pointset

### ISSUE THREAD

**Issue by sepidehamiri** [InsightSoftwareConsortium/ITKElastix#146]
Hello ITKElastix team,

Thank you very much for your useful library. I want to try the 3D mask registration based on 4 points. My code is as follows. But when I try with and without a pointset, the output is the same.

```
for m in a:
    for n in b:
        fixed_image = itk.imread(f'mask_prepration_registration_corect/image{m}.nii.gz', itk.F)
        moving_image = itk.imread(f'mask_prepration_registration_corect/image{n}.nii.gz', itk.F)

        moving_mask = itk.imread(f'mask_prepration_registration_corect/mask{n}.nii.gz', itk.F)
        parameter_object = itk.ParameterObject.New()
        parameter_map_rigid = parameter_object.GetDefaultParameterMap('rigid')
        parameter_object.AddParameterMap(parameter_map_rigid)
        parameter_map_affine = parameter_object.GetDefaultParameterMap('affine')
        parameter_object.AddParameterMap(parameter_map_affine)
        parameter_map_bspline = parameter_object.GetDefaultParameterMap('bspline')
        parameter_object.AddParameterMap(parameter_map_bspline)

        result_image, result_transform_parameters = itk.elastix_registration_method(
            fixed_image, moving_image,
            fixed_point_set_file_name=f'data/landmarks/targets{m}.txt',
            moving_point_set_file_name=f'data/landmarks/targets{n}.txt',
            parameter_object=parameter_object,
            log_to_console=False)

        result_transform_parameters.SetParameter('FinalBSplineInterpolationOrder', '0')
        result_moving_mask = itk.transformix_filter(moving_mask, result_transform_parameters)

        itk.imwrite(result_moving_mask, f'masks_registration_result/{m}/reg_{m}_{n}.nii.gz')
```

Where is my solution wrong?

**Comment by dzenanz** [comment]
If fixed and moving images are provided, maybe the point sets are ignored? Somebody who knows elastix better could answer this authoritatively. You can also test it by removing `fixed_image, moving_image,` parameters.

**Comment by sepidehamiri** [comment]
> If fixed and moving images are provided, maybe the point sets are ignored? Somebody who knows elastix better could answer this authoritatively. You can also test it by removing `fixed_image, moving_image,` parameters.

Thank you for your quick reply. But in examples 5 and 9, the images and point sets are given together. I get this error when I remove `fixed_image` and `moving_image`:

`ITK ERROR: ElastixRegistrationMethod(0x654ae30): Input FixedImage is required but not set.`


I get this error when I only put fixed_image:

`TypeError: Expecting argument of type itkImageF2 or itkImageSourceIF2.`

**Comment by NHPatterson** [comment]
I believe you have to specific registration parameters that include point based metrics:

Developer docs on the metric:
https://elastix.lumc.nl/doxygen/classelastix_1_1CorrespondingPointsEuclideanDistanceMetric.html

This link has some info and code from simpleelastix which is, N.B., not fully transferable but the principle is the same: 
https://simpleelastix.readthedocs.io/PointBasedRegistration.html

A good strategy may be to make to make two rigid parameter maps, the first with the corresponding points distance metric, and the second without. This workflow assumes your first rigid will use the corresponding points, find a good registration, then proceed with fully automatic approaches.

Heath

**Comment by ViktorvdValk** [comment]
Indeed, [example 5 ](https://github.com/InsightSoftwareConsortium/ITKElastix/blob/master/examples/ITK_Example05_PointRegistration.ipynb) shows how to create a parameter map with the correct metrics in this case.
Keep in mind that example 5 shows how to use a point set to help the registration of images, and example 9 shows how to transform the point sets.

**Comment by sepidehamiri** [comment]
> I believe you have to specify registration parameters that include point based metrics.
> 
> Developer docs on the metric: https://elastix.lumc.nl/doxygen/classelastix_1_1CorrespondingPointsEuclideanDistanceMetric.html
> 
> This link has some info and code from simpleelastix which is, N.B., not fully transferable but the principle is the same: https://simpleelastix.readthedocs.io/PointBasedRegistration.html
> 
> A good strategy may be to make to make two rigid parameter maps, the first with the corresponding points distance metric, and the second without. This workflow assumes your first rigid will use the corresponding points, find a good registration, then proceed with fully automatic approaches.
> 
> Heath

I added the following line and the problem was solved! Thank you very much for your help.

```
        parameter_map_rigid['Metric'] = [original_metric[0],
                                         'CorrespondingPointsEuclideanDistanceMetric']
```

**Comment by sepidehamiri** [comment]
> Indeed, [example 5 ](https://github.com/InsightSoftwareConsortium/ITKElastix/blob/master/examples/ITK_Example05_PointRegistration.ipynb) shows how to create a parameter map with the correct metrics in this case. Keep in mind that example 5 shows how to use a point set to help the registration of images, and example 9 shows how to transform the point sets.

You were absolutely right. I didn't notice this difference.
