### ISSUE TITLE
Reduce wheel size below 100MB

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKElastix#151]
With v0.14.0,`itk_elastix-0.14.0-cp310-cp310-win_amd64.whl` is 119MB and therefore over the PyPI limit. I yanked the release as only 2 wheels were uploaded.

**Comment by NHPatterson** [comment]
It's also possible to ask for an increase in file size on PyPI by filing a specific request on the pypi support github.

https://github.com/pypa/pypi-support/issues/new?assignees=&labels=limit+request&template=limit-request-file.yml&title=File+Limit+Request%3A+PROJECT_NAME+-+000+MB

**Comment by dzenanz** [comment]
Done: https://github.com/pypa/pypi-support/issues/1888.

**Comment by dzenanz** [comment]
The PyPI file limit was increased to 200MB, so we will not need to alter things in the near future. [Wheels](https://pypi.org/manage/project/itk-elastix/release/0.14.0/) are now available.
