### ISSUE TITLE
fileiotype in extras.py should include list (?)

### ISSUE THREAD

**Issue by michaelidis** [InsightSoftwareConsortium/ITKElastix#166]
Should not fileiotype include list type? As in 
`
fileiotype = Union[str, bytes, os.PathLike, list[str]]
`

Otherwise you never get to 
`
if type(filename)  in [list, tuple]:
`
in imread():
`
def imread(
    filename: fileiotype,
    pixel_type: Optional["itkt.PixelTypes"] = None,
    fallback_only: bool = False,
    imageio: Optional["itkt.ImageIOBase"] = None,
) -> "itkt.ImageBase":
`

**Comment by thewtex** [comment]
@michaelidis yes, you are correct. Please review this patch: https://github.com/InsightSoftwareConsortium/ITK/pull/3693

**Comment by michaelidis** [comment]
thanks!
