### ISSUE TITLE
itk-elastix version 0.14.3 results in segmentation fault

### ISSUE THREAD

**Issue by Svdvoort** [InsightSoftwareConsortium/ITKElastix#177]
After installing the newest version of `itk-elastix`, 0.14.3, I get a segmentation fault with the most basic of operations. This was not an issue with version 0.14.1

A MWE:

```
import itk

parameters = itk.ParameterObject.New()
```

This results in `Segmentation fault (core dumped)` on 0.14.3, but runs fine on 0.14.1.

Tested on Ubuntu 18.04 with a completely clean environment. 
Results of pip freeze:

```
itk==5.3rc4.post4
itk-core==5.3rc4.post4
itk-elastix==0.14.3
itk-filtering==5.3rc4.post4
itk-io==5.3rc4.post4
itk-numerics==5.3rc4.post4
itk-registration==5.3rc4.post4
itk-segmentation==5.3rc4.post4
numpy==1.21.6
```

**Comment by tbirdso** [comment]
Hi @Svdvoort , thank you for raising this issue. An updated version `itk-elastix==0.14.4` has been published which is compatible with the ITK v5.3rc04.post4 prerelease. Python notebook checks are passing again with this release.
