### ISSUE TITLE
itk-elastix 0.15.0 release has no installation for python 3.8 and python 3.9

### ISSUE THREAD

**Issue by Svdvoort** [InsightSoftwareConsortium/ITKElastix#181]
The 0.15.0 release of itk-elastix has no install candidates for python 3.8 and python 3.9.
Looking at the [pypi files](https://pypi.org/project/itk-elastix/0.15.0/#files) there are install candidates for python 3.7, 3.10 and 3.11 but only 3.8 and 3.9 are missing.

**Comment by dzenanz** [comment]
It could be another manifestation of https://github.com/InsightSoftwareConsortium/ITKPythonPackage/issues/235?

**Comment by tbirdso** [comment]
The CI PyPI upload workflow failed due to exceeded file size limits:

https://github.com/InsightSoftwareConsortium/ITKElastix/actions/runs/3577645998/jobs/6022259374

```
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Project size too large. Limit for project 'itk-elastix' total size is  
         10 GB. See https://pypi.org/help/#project-size-limit       
```

It looks like 3.10, 3.11, and then 3.7 were uploaded successfully and the size limit was hit at 3.8, thus 3.9 was not attempted.

I am uncertain whether these particular packages are larger for some reason or if the 5.3 update somehow narrowly put `itk-elastix` over the 10GB limit. Perhaps @thewtex could weigh in on managing PyPI package sizes?

**Comment by dzenanz** [comment]
If we remove some older versions from PyPI, that would create space for the latest version. Or maybe remove some beta/RC versions? Or some minor versions? Or ask PyPI maintainers to increase the limit for the project?

**Comment by tbirdso** [comment]
@dzenanz I'm good with any of the solutions you've proposed. It looks like @thewtex removed several ITK module release candidates on PyPI recently, probably to make room for the v5.3.0 release? https://pypi.org/project/itk-numerics/#history

It will fall to one of the `itk-elastix` PyPI maintainers (@dzenanz  @hjmjohnson @thewtex ) to decide what packages should be dropped from PyPI.

**Comment by dzenanz** [comment]
I prefer Matt to chime in or decide what to sack.

**Comment by thewtex** [comment]
Yes, we just hit the default 10 GB limit, stopping the uploads.

Yes, I had to delete a few old `itk-` release candidate packages to keep under the size limit.

I created a request to increase the `itk-elastix` size limit here: https://github.com/pypa/pypi-support/issues/2449

In the meantime, I also deleted the oldest releases, and I will restart the CI build. Hopefully they will upload.

**Comment by tbirdso** [comment]
@thewtex It looks like Linux and MacOS Python 3.8 packages were uploaded, but the size limit was exceeded before Windows 3.8 or any 3.9 packages were uploaded: https://pypi.org/project/itk-elastix/#files

**Comment by thewtex** [comment]
I deleted a few more releases and restarted the Action.

**Comment by thewtex** [comment]
Related, we should also address #182 #183

**Comment by tbirdso** [comment]
Looks like we are just missing Windows 3.9 packages now.

**Comment by thewtex** [comment]
Third time's the charm :gem:
