### ISSUE TITLE
Disable installation of libraries and headers for the Python wheel

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKElastix#183]
With ongoing developments in scikit-build, we will eventually be able to build against packages. For now, though, we cannot, and these increase the size of the wheels significantly. Disable installation of libraries and headers. Create a new issue to provide the installation of a `itk-elastix-dev` package that includes these in the future.

**Comment by thewtex** [comment]
I agree that `NOT NO_INSTALL_xxx` is more direct, although this naming scheme is traditionally used in CMake (ITK in the past, VTK). We could change it, though. Would you like it changed?

**Comment by N-Dekker** [comment]
Thanks Matt. Do you have a pointer/reference that such `NOT NO_INSTALL_xxx` is still commonly used? Otherwise, I'd rather go for the positive approach, `if INSTALL_xxx`

**Comment by thewtex** [comment]
@N-Dekker here are a few references:

- https://github.com/InsightSoftwareConsortium/ITK/blob/476f31db2a32bf1663e02d5682b8cb5cc20f9e36/CMake/ITKModuleMacros.cmake#L432
- https://github.com/Kitware/VTK/blob/4b06dd2b2f6a953de1d2e6ef38dd678b16b05f8e/CMake/vtkModule.cmake#L3438

**Comment by N-Dekker** [comment]
@thewtex Thanks for clarifying to me that `NOT NO` is the traditional way to express "yes"!  👍

**Comment by thewtex** [comment]
Resolved via #186 #192
