### ISSUE TITLE
An error message appears on itkelastix running in ubuntu

### ISSUE THREAD

**Issue by weil0258** [InsightSoftwareConsortium/ITKElastix#189]
error :  PyCapsule_Import "_ITKCommonPython._C_API" is not valid 
How to solve?

**Comment by thewtex** [comment]
Please upgrade to the latest version of `itk-elastix` in a fresh environment.

**Comment by tbirdso** [comment]
Hi @weil0258 , following up, this issue should be resolved by updating to the latest `itk` and `itk-elastix` distributions:
```sh
python -m pip install --upgrade itk itk-elastix
```

If you continue to see the error please re-open this issue and include the following details:
- The version of Ubuntu you are using
- The version of Python you are using
- The versions of the `itk` and `itk-elastix` packages you are using
- A minimum reproducible example
