### ISSUE TITLE
Speed up the initialisation of a new ParameterObject

### ISSUE THREAD

**Issue by MartinKjunior** [InsightSoftwareConsortium/ITKElastix#204]
Using the simple testing code
```import itk
from time import time

start = time()
test = itk.ParameterObject.New()
print(time() - start)
```
it takes between 20-30 seconds (last two tests took 22 and 28s) to initialise the `itk.ParameterObject` for the first time. It get faster subsequently. Fetching the default parameter map from SimpleElastix `sitk.GetDefaultParameterMap()` works without having to wait a long time unlike the case of `itk.ParameterObject.New()`. Is this initial delay necessary or could it be improved?

**Comment by dzenanz** [comment]
ITK Python, and therefore ITKElastix, are lazily initialized. Libraries are not loaded until they are needed, and the first time you ask for something it is slow. You can avoid it by invoking `itk.force_load()`.

**Comment by dzenanz** [comment]
ITKElastix is a library variant of Elastix, and as such does not need an Elastix application.

I think that SimpleITK is distributed as one file, which is easier and somewhat faster to load than dozens of smaller libs. The sacrifice is increased memory consumption, and load time not proportional to amount of functionality needed.

**Comment by MartinKjunior** [comment]
> ITKElastix is a library variant of Elastix, and as such does not need an Elastix application.
> 
> I think that SimpleITK is distributed as one file, which is easier and somewhat faster to load than dozens of smaller libs. The sacrifice is increased memory consumption, and load time not proportional to amount of functionality needed.

All that makes sense. Thank you for the prompt reply :)
