### ISSUE TITLE
Remove Python 3.7 from the CI

### ISSUE THREAD

**Issue by N-Dekker** [InsightSoftwareConsortium/ITKElastix#213]
It appears that the CI takes too much time now (leading to timeouts, after 6 hours of building), as we discussed from here: https://github.com/InsightSoftwareConsortium/ITKElastix/pull/211#issuecomment-1544098511  The CI now builds the following 11 [artifacts](https://github.com/InsightSoftwareConsortium/ITKElastix/actions/runs/4907878277#artifacts):

 - LinuxWheel37
 - LinuxWheel38
 - LinuxWheel39
 - LinuxWheel310
 - LinuxWheel311
 - MacOSWheels
 - WindowsWheel3.7
 - WindowsWheel3.8
 - WindowsWheel3.9 
 - WindowsWheel3.10
 - WindowsWheel3.11

Next month (2023-06-27) Python 3.7 will reach "end of life": https://devguide.python.org/versions/  So it does not seem necessary anymore to build WindowsWheel3.7 and LinuxWheel37 with each push and each merge to the main branch.

**Comment by tbirdso** [comment]
@N-Dekker Thanks for pointing out that Python 3.7 is reaching end of life. I will make that change available across projects in the ITK Python reusable workflow.

Note that per mention in https://github.com/InsightSoftwareConsortium/ITKElastix/pull/211#issuecomment-1544133228 ITK Python CI job runtimes currently tend to perform differently based on target architecture, not Python version. In #211 those jobs building for Linux aarch64 platforms tend to take 6 hours or more, while jobs building for Linux x86_64 platforms took less than an hour. In the future we aim to speed things up, but the current feasible path for aarch64 builds on non-self-hosted GitHub Actions runners requires platform emulation which is significantly slower than native x64 builds.

I would suggest evaluating the cost/benefit of having aarch64 builds on ITKElastix and pursue one of the following paths accordingly:
- Remove aarch64 builds
- Limit aarch64 builds to run in the `master` branch only
- Pay for self-hosted aarch64 runners to avoid platform emulation (consider https://cirun.io/)

cc @thewtex @dzenanz

**Comment by N-Dekker** [comment]
Thank you for your extensive reply, Tom. For me, it would be very helpful already if aarch64 builds would no longer run on PR branches. I guess that would mean that only `main` branch builds would keep having those timeouts, right?

Of course, it would then still be somewhat disappointing to keep having those build failures at the `main` branch.

**Comment by mstaring** [comment]
why not remove them altogether? We can always reenable later, once build times are resolved.

**Comment by tbirdso** [comment]
@mstaring I agree that would be the most straightforward workaround here. I guess I am trying to understand whether someone has an immediate use case for ITKElastix aarch64 wheels that require those wheels to be built, or if it will not be too disruptive to remove them.

Maybe @thewtex can weigh in?

**Comment by thewtex** [comment]
Agreed, disabling the aarch64 wheels builds for now is a reasonable approach. And re-enable later when we have aarch64 cross-compiles.

In the bigger picture, the wasm builds will also help. These work across windows/mac/linux on amd64 but also mac/linux on arm. And a single build works across all Python versions 3.7+.
https://itkwasm.readthedocs.io/en/latest/introduction.html

**Comment by thewtex** [comment]
Python 3.7 is no longer built in the CI via configuration updates for ITK 5.4 RC 1, e.g. https://github.com/InsightSoftwareConsortium/ITKElastix/pull/236
