### ISSUE TITLE
Use saved registration to apply for new images

### ISSUE THREAD

**Issue by cagatayalici** [InsightSoftwareConsortium/ITKElastix#233]
Hi!

Suppose I registered image 1 and image 2. How can I save registration parameters such that I can reuse them for other images or for the same pair at a later time?

Thank you.
Best

**Comment by dzenanz** [comment]
This example shows how to do that:
https://github.com/InsightSoftwareConsortium/ITKElastix/blob/main/examples/ITK_Example08_SimpleTransformix.ipynb
