### ISSUE TITLE
macOS arm packages missing for 0.18.0

### ISSUE THREAD

**Issue by berendkleinhaneveld** [InsightSoftwareConsortium/ITKElastix#242]
Just noticed that there are no macOS ARM packages for 0.18.0 on PyPI. Is this deliberate or has something gone wrong?

**Comment by thewtex** [comment]
Hi, since GitHub Actions runners are not available for macOS ARM, we have to manually build them -- we plan to upload an arm wheel with the next release.

**Comment by berendkleinhaneveld** [comment]
Thanks for the explanation!

**Comment by thewtex** [comment]
0.19.0 for ARM mac has been pushed to PyPI. There are also [experimental WebAssembly packages](https://pypi.org/project/itkwasm-elastix/) that work on ARM mac.
