### ISSUE TITLE
Saving and Loading Paramter files to reapply transfomr

### ISSUE THREAD

**Issue by haidermri** [InsightSoftwareConsortium/ITKElastix#251]
I would like to save a parameter map file and then load it later to reapply a transform to other move images

 I am having figuring out how to do this

Here is how the file to be saved (transfn) is created:
            registered_image, params = itk.elastix_registration_method(fixed_image, moving_image, 
                                                                       parameter_object=parameter_object,
                                                                       log_to_console=False)
            parameter_map = params.GetParameterMap(0)
            params.WriteParameterFile(parameter_map,transfn)

When I try to load transfn and apply it later using:

            par_obj1 = itk.ParameterObject.New()
            trparams= par_obj1.ReadParameterFile(transfn)
            registered_image = itk.transformix_filter(anothermoveingimage,par_obj1)
            finalmove = itk.GetArrayFromImage(registered_image)

I get the error
  File "", line 138, in fCoregwithMask
    finalmove = itk.GetArrayFromImage(registered_image)
  File "", line 335, in GetArrayFromImage
    return _GetArrayFromImage(
  File "C:\miniconda3\envs\nnunetv2\lib\site-packages\itk\support\extras.py", line 314, in _GetArrayFromImage
    raise RuntimeError("No suitable template parameter can be found.")

registered image has the following shape and type
(264, 289, 86)
<class 'itk.itkPyBufferPython.NDArrayITKBase'>

**Comment by thewtex** [comment]
Hi,

Are you using the recently released itk-elastix 0.19.0? If not, please upgrade.

What is `print(registered_image)` and `print(type(registered_image))`?

**Comment by haidermri** [comment]
I ma running 0.180
I will update. Thanks

This ended up working without an update
finalmove = np.asarray(registered_image)
instead of
itk.GetArrayFromImage(registered_image)
