### ISSUE TITLE
itk.ParameterObject -> seg fault in fresh env

### ISSUE THREAD

**Issue by karchern** [InsightSoftwareConsortium/ITKElastix#282]
I've been using itk-elastix for a while but have recently run into issues setting up my envirnoment. Specifically, setting up itk-elastix in a fresh environment leads to a broken installation for me. 

To reproduce, doing this:

```
conda create -y -n test python=3.10
pip install itk-elastix
```

and then executing a python file with

```
import itk
itk.ParameterObject
```

leads to a segmentation fault. 

Any help strongly recommended as this is making me loose my mind slowly

Edit: I compared the setup to my working environment (that I've set up  half a year ago), and I discovered that pinning itk to `5.4rc2` (instead of the most up to date, by default installed versioin of `5.4rc4`) fixes the issue.

so this generates a functioning environment

```
conda create -y -n test python=3.10
pip install itk-elastix itk==5.4rc2
```

I'm not quite sure what's going on or why I haven't found other people reporting this issue. If you'd like me to provide with error logs, versions etc to get to the bottom of this, I'd be happy to help out.

**Comment by dzenanz** [comment]
Is #265 related?

**Comment by thewtex** [comment]
@karchern please try `itk-elastix` 0.19.2 and `itk` 5.4rc4` and let us know how it goes.

**Comment by dzenanz** [comment]
Can this be closed now?

**Comment by karchern** [comment]
yes - thanks to both of you!
