### ISSUE TITLE
object-oriented interface similar to SimpleElastix

### ISSUE THREAD

**Issue by romangrothausmann** [InsightSoftwareConsortium/ITKElastix#35]
Is there the possibility to make use of ITKElastix with an object-oriented interface similar to SimpleElastix (as described here: https://simpleelastix.readthedocs.io/HelloWorld.html)?
For example to transfer an SE script to ITKElastix, I am looking for the correct way to translate e.g. these lines:
https://github.com/romangrothausmann/elastix_scripts/blob/ba86940716bacfed96641a48a39053014519cb54/recRegStack.py#L153-L157

**Comment by romangrothausmann** [comment]
For making use of the procedural interface, would I have to accumulate all settings first and then provide all at
https://github.com/romangrothausmann/elastix_scripts/blob/ba86940716bacfed96641a48a39053014519cb54/recRegStack.py#L222 ?

**Comment by romangrothausmann** [comment]
The answer seems to be given here:
https://itkpythonpackage.readthedocs.io/en/latest/Quick_start_guide.html#instantiate-an-itk-object
e.g. `selx = itk.ElastixRegistrationMethod[rType, rType].New()`

**Comment by romangrothausmann** [comment]
Solved, but making use of the object-oriented interface in e.g. 
https://github.com/InsightSoftwareConsortium/ITKElastix/blob/97c9c6e1e858969b449034a48ff8bb7a57987ecd/examples/0_HelloRegistrationWorld.ipynb
might help others to learn about this possibility.

**Comment by thewtex** [comment]
> The answer seems to be given here:
https://itkpythonpackage.readthedocs.io/en/latest/Quick_start_guide.html#instantiate-an-itk-object
e.g. selx = itk.ElastixRegistrationMethod[rType, rType].New()

Yes, that's correct.

> Solved, but making use of the object-oriented interface in e.g.
https://github.com/InsightSoftwareConsortium/ITKElastix/blob/97c9c6e1e858969b449034a48ff8bb7a57987ecd/examples/0_HelloRegistrationWorld.ipynb
might help others to learn about this possibility.

Thanks for the feedback -- we may demonstrate the object-oriented interface in future notebooks.
