### ISSUE TITLE
module 'itk' has no attribute 'imread'

### ISSUE THREAD

**Issue by henryhuangrui** [InsightSoftwareConsortium/ITKElastix#42]
hi, I just installed the itk_elastix_opencl as the way you said  :
          `pip install itk-elastix-opencl` 
and I got `Attribute Error:module 'itk' has no attribute 'imread'` 
when i do `fixed_image = itk.imread('path/to/fixed_image.mha')`,why i got this issue?

**Comment by dzenanz** [comment]
Maybe explain what was the problem, in case somebody else runs into it.

**Comment by henryhuangrui** [comment]
it was a mistake ,i named the python file as itk.py, then mistake happened..
