### ISSUE TITLE
Getting the result image in the object oriented approach fails

### ISSUE THREAD

**Issue by romangrothausmann** [InsightSoftwareConsortium/ITKElastix#51]
`GetOutput()` is shadowed from `ImageToImageFilter`.

**Comment by romangrothausmann** [comment]
Probably solved with #40, but currently not able to test it due to issues mentioned in https://github.com/InsightSoftwareConsortium/ITKElastix/pull/40#issuecomment-617643475.

**Comment by romangrothausmann** [comment]
@thewtex does https://github.com/InsightSoftwareConsortium/ITK/pull/1927 related to https://github.com/InsightSoftwareConsortium/ITKElastix/pull/40#issuecomment-619270415?
If not, should I open a new issue to track those of https://github.com/InsightSoftwareConsortium/ITKElastix/pull/40#issuecomment-617643475?

**Comment by thewtex** [comment]
> issues mentioned in #40 (comment).

Some WIP to update elastix to 5.1.0 is here:

  https://github.com/SuperElastix/elastix/pull/245

> @thewtex does InsightSoftwareConsortium/ITK#1927 related to #40 (comment)?

Those are unrelated

**Comment by romangrothausmann** [comment]
Many thanks @thewtex for the explanations and updates.

**Comment by thewtex** [comment]
@N-Dekker is helping to update elastix in https://github.com/SuperElastix/elastix/pull/245

**Comment by thewtex** [comment]
Should be addressed in `itk-elastix` *0.7.0*.
