### ISSUE TITLE
How can I get the BSspline transform and apply to other images?

### ISSUE THREAD

**Issue by zhuczhuc** [InsightSoftwareConsortium/ITKElastix#56]
Hi, I want to use BSpline DIR, and get the transform. I can get the transform parameters in examples/2_RegistrationParameters.ipynb, but how can I apply it to other images in the same coordinates. 
Like in elastix, transformix cmd can finish this. Is there any pure python code?

**Comment by dzenanz** [comment]
A dozen new [examples](https://github.com/InsightSoftwareConsortium/ITKElastix/tree/master/examples) have been [recently added](https://github.com/InsightSoftwareConsortium/ITKElastix/pull/57). Do any of them help you?

**Comment by drchrisch** [comment]
The examples are quite helpful. However, this one "ITK_Example9_SimpleTransformix.ipynb" seems to work only using the included sample data but it fails with 3D data. Please, see the notebook [https://github.com/drchrisch/unresolved-stuff/blob/master/1_NumPyArray-Copy1.ipynb](url) for details.
Any ideas how to get it to work?

**Comment by zhuczhuc** [comment]
> A dozen new [examples](https://github.com/InsightSoftwareConsortium/ITKElastix/tree/master/examples) have been [recently added](https://github.com/InsightSoftwareConsortium/ITKElastix/pull/57). Do any of them help you?

The new exampples is great. But I have the same problem with @drchrisch ,3D data fails. The log shows " TypeError: Expecting argument of type itkImageF2 or itkImageSourceIF2.". My itk-elastix version is 0.6.3.

**Comment by drchrisch** [comment]
Well, my installation should be up-to-date and for "itk" it says: packages in environment at C:\Users\...\Miniconda3\envs...:
#### Name                    Version                   Build  Channel
itk                       5.1.1                    pypi_0    pypi
itk-core                  5.1.1                    pypi_0    pypi
itk-elastix               0.6.3                    pypi_0    pypi
itk-filtering             5.1.0.post3              pypi_0    pypi
itk-io                    5.1.0.post3              pypi_0    pypi
itk-numerics              5.1.0.post3              pypi_0    pypi
itk-registration          5.1.0.post3              pypi_0    pypi
itk-segmentation          5.1.0.post3              pypi_0    pypi
itkwidgets                0.32.0           py37hc8dfbb8_0    conda-forge


Did you try the 3D toy example?

**Comment by thewtex** [comment]
`itk-elastix` *0.7.0* has support for this with the `itk.transformix_filter` function. See:

https://github.com/InsightSoftwareConsortium/ITKElastix/blob/master/examples/ITK_Example08_SimpleTransformix.ipynb
