### ISSUE TITLE
SetFixedImage doesn't work for 3D images

### ISSUE THREAD

**Issue by JSousa-UoL** [InsightSoftwareConsortium/ITKElastix#64]
I was having a look at the notebooks (good way to start learning on how to use this package) and trying to run some of them.
 
I tried the 3D registration example with some data I have and it returns the following error at itk.ElastixRegistrationMethod.New().SetFixedImage: Expecting argument of type itkImageF2 or itkImageSourceIF2.
I tried this after loading a 3D nifti image using imread - itk.itkImagePython.itkImageF3.

Does this mean it's not possible to run registration in 3D images using the elastix filter?

**Comment by drchrisch** [comment]
Registration 3D images works fine (not only with an image dummy [https://github.com/drchrisch/unresolved-stuff/blob/master/1_NumPyArray-Copy1.ipynb](url)) but also using tif files. However, I am unable to apply the calculated transformation params to another 3D image. Did you try this?

**Comment by drchrisch** [comment]
Well, in fact, it does work in 3D. See Example_10 for details.

**Comment by thewtex** [comment]
Currently, the registration method is available only for `float` images, though we are working to expand support re: https://github.com/SuperElastix/elastix/issues/322.

Until then, read in the image with a float pixel type with:

```
fixed_image = itk.imread('my_image.mha', itk.F)
```

**Comment by JSousa-UoL** [comment]
I'm using the command you suggested and it's still not working. However, to be honest I don't know if the Nifti file contains double or float data. I'll keep an eye on the link you provided

**Comment by ViktorvdValk** [comment]
If you follow [Example 3](https://github.com/InsightSoftwareConsortium/ITKElastix/blob/master/examples/ITK_Example03_Masked_3D_Registration.ipynb) , you should not get the error you provided. That error was due to a wrong initialization in the previous example notebooks, which is now fixed. 

'itk.ElastixRegistrationMethod.New(fixed_image, moving_image)'  is correct

**Comment by JSousa-UoL** [comment]
I see, I installed the most recent version and I'm not getting that error anymore after following your advice. You may close this issue.
