### ISSUE TITLE
Deformation Field calculation not possible with procedural method of Transformix

### ISSUE THREAD

**Issue by ViktorvdValk** [InsightSoftwareConsortium/ITKElastix#73]

**Comment by thewtex** [comment]
It may be helpful to create these functions in a separate *.py* file.

The functions can be injected into the packaged Python module by adding CMake code after line 2 here:

https://github.com/InsightSoftwareConsortium/ITKElastix/blob/6a4dd1d3ccf58303d5747508bf2be3785f014be6/wrapping/CMakeLists.txt#L2

that reads the code from the file with CMake's `file(READ [...]`.

https://cmake.org/cmake/help/latest/command/file.html

then adding the file's content to the `ITK_WRAP_PYTHON_LIBRARY_IMPORTS` variable. For example:

```
file(READ ${CMAKE_CURRENT_SOURCE_DIR}/extra_functions.py extra_functions)
set(ITK_WRAP_PYTHON_LIBRARY_IMPORTS "${extra_functions}\n${ITK_WRAP_PYTHON_LIBRARY_IMPORTS}")
```

**Comment by thewtex** [comment]
xref #82

**Comment by ViktorvdValk** [comment]
temporary fix, still uses Disk IO, works fine
