### ISSUE TITLE
Problem using ITKElastix in another ITK remote module

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKElastix#86]
I am trying to use ITKElastix from [HASI](https://github.com/dzenanz/HASI/commit/db537e43fe4f3d9f852df64809f633fef96d5532). To accomplish this, I am [adding ITKElastix as a remote module](https://github.com/dzenanz/ITK/commit/4727213365b71b35c54a7295e94be339cbaea952) to ITK. ITK builds fine, but HASI runs into link errors (cannot find `elastix_lib.lib`). In an attempt to fix this, I tried adding [CMake export code](https://github.com/dzenanz/ITKElastix/commit/be179e9b09c763d2d7bd45e29fd58e302d8a9b86) to ITKElastix, but this causes circular dependency of `transformix_lib` and `elastix_lib` when trying to generate ITK project from CMake:

```text
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
Running module dependency checks
Enabled BoneEnhancement, requested by Module_BoneEnhancement.
Enabled Cuberille, requested by Module_Cuberille.
Enabled Elastix, requested by Module_Elastix.
Enabled ITKAnisotropicSmoothing, requested by ITK_BUILD_DEFAULT_MODULES.
Enabled ITKAntiAlias, requested by ITK_BUILD_DEFAULT_MODULES.
...
Enabled ITKVtkGlue, requested by Module_ITKVtkGlue.
Enabled ITKWatersheds, requested by ITK_BUILD_DEFAULT_MODULES.
Enabled ITKZLIB, requested by ITK_BUILD_DEFAULT_MODULES.
Elastix_LIBRARIES: elastix_lib;transformix_lib
elx_BINARY_DIR: C:/Dev/ITK-git-2015/_deps/elx-build
Checking for InitOnceExecuteOnce:
Performing Test InitOnceExecuteOnce - Success
Warnings Configuration:
Filter ZLIB is ON
Could NOT find Perl (missing: PERL_EXECUTABLE) 
Configuring done
CMake Error at C:/Dev/ITK-git-2015/_deps/elx-src/Core/CMakeLists.txt:184 (add_library):
  Target "transformix_lib" links to itself.

CMake Error at C:/Dev/ITK-git-2015/_deps/elx-src/Core/CMakeLists.txt:184 (add_library):
  Target "transformix_lib" links to itself.

CMake Error at C:/Dev/ITK-git-2015/_deps/elx-src/Core/CMakeLists.txt:154 (add_library):
  Target "elastix_lib" links to itself.

CMake Error at C:/Dev/ITK-git-2015/_deps/elx-src/Core/CMakeLists.txt:154 (add_library):
  Target "elastix_lib" links to itself.

CMake Error at C:/Dev/ITK-git-2015/_deps/elx-src/Core/CMakeLists.txt:154 (add_library):
  Target "elastix_lib" links to itself.

CMake Error at C:/Dev/ITK-git-2015/_deps/elx-src/Core/CMakeLists.txt:184 (add_library):
  Target "transformix_lib" links to itself.

Generating done
```

**Comment by dzenanz** [comment]
Initial and incremental builds seem to behave differently. The only idea I have is to rename ITKElastix from `Elastix` into something different (`ElastixRM`?) to reduce confusion and make debugging this easier.

**Comment by thewtex** [comment]
> Initial and incremental builds seem to behave differently. The only idea I have is to rename ITKElastix from Elastix into something different (ElastixRM?) to reduce confusion and make debugging this easier.

I am not following the issue. What is the issue, and how does the proposed change help?

> CMake Error at C:/Dev/ITK-git-2015/_deps/elx-src/Core/CMakeLists.txt:184 (add_library):
  Target "transformix_lib" links to itself.

We may be able to avoid this be specifying the `ITK` `COMPONENTS` required in these locations:

https://github.com/InsightSoftwareConsortium/ITKElastix/blob/532a3fe493540ab691ba8818e66a3b316ffb7ccd/CMakeLists.txt#L33
 https://github.com/SuperElastix/elastix/blob/90122eff6b37a17adc9f5bb3d7bc08608e9c14a6/CMakeLists.txt#L26

**Comment by dzenanz** [comment]
Now I see what is the problem: there is a true circular dependency. Elastix depends on ITK, and if ITK tries to depend on it via a remote module, the circle of dependence is complete. Just specifying components does not help, because `ITKConfig.cmake` contains `set(ITK_MODULES_ENABLED "ITKDoubleConversion;...;Elastix;...;ITKWatersheds")` and later `itk_module_config(ITK ${ITK_MODULES_ENABLED})`. The first time `ITKElastix` is enabled the in-source build can complete. But not subsequently.

One way to resolve this is for HASI to not be an ITK remote module, and just be an application which depends on ITK and Elastix (not good). Maybe another is for Elastix to have its own separate build of ITK (bad). The last is to merge ITKElastix into Elastix, so Elastix can behave as a remote module when being built as part of ITK (requires cooperation of Elastix maintainers).

**Comment by thewtex** [comment]
> set(ITK_MODULES_ENABLED "ITKDoubleConversion;...;Elastix;...;ITKWatersheds") and later

Right - if `COMPONENTS` is specified, `Elastix` will not be included per:

https://github.com/InsightSoftwareConsortium/ITK/blob/71c0bb375a3fcbc909e20e20c57bbfe6a672dd0b/CMake/ITKConfig.cmake.in#L81-L85

**Comment by dzenanz** [comment]
[Specifying components](https://github.com/SuperElastix/elastix/pull/360) indeed resolves circular dependency when building ITK.

But the link error `LINK : fatal error LNK1104: cannot open file 'elastix_lib.lib'` in HASI (log below) persists even with [CMake export code](https://github.com/dzenanz/ITKElastix/commit/59f14a82cecdbe6e3fe80212b6b76885ca5a2476). `elastix_lib.lib` does not exists, but `C:\Dev\ITK-git-2015\lib\Debug\elastix-5.0.lib` does. Maybe we need to do something different from [this](https://github.com/InsightSoftwareConsortium/ITKElastix/blob/e01e6089f4768c5796a656c6b3608e74ce93933f/CMakeLists.txt#L9)?

```text
Build started...
1>------ Build started: Project: HASIHeaderTest1, Configuration: Debug x64 ------
2>------ Build started: Project: HASITestDriver, Configuration: Debug x64 ------
3>------ Build started: Project: ITKData, Configuration: Debug x64 ------
4>------ Build started: Project: ClangFormat, Configuration: Debug x64 ------
5>------ Build started: Project: HASIHeaderTestClean, Configuration: Debug x64 ------
6>------ Skipped Build: Project: Continuous, Configuration: Debug x64 ------
6>Project not selected to build for this solution configuration 
7>------ Skipped Build: Project: Experimental, Configuration: Debug x64 ------
7>Project not selected to build for this solution configuration 
8>------ Skipped Build: Project: Nightly, Configuration: Debug x64 ------
8>Project not selected to build for this solution configuration 
9>------ Skipped Build: Project: NightlyMemoryCheck, Configuration: Debug x64 ------
9>Project not selected to build for this solution configuration 
10>------ Skipped Build: Project: RUN_TESTS, Configuration: Debug x64 ------
10>Project not selected to build for this solution configuration 
11>------ Skipped Build: Project: ITKHeaderTests, Configuration: Debug x64 ------
11>Project not selected to build for this solution configuration 
1>LINK : fatal error LNK1104: cannot open file 'elastix_lib.lib'
1>Done building project "HASIHeaderTest1.vcxproj" -- FAILED.
2>LINK : fatal error LNK1104: cannot open file 'elastix_lib.lib'
2>Done building project "HASITestDriver.vcxproj" -- FAILED.
12>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
12>Project not selected to build for this solution configuration 
========== Build: 3 succeeded, 2 failed, 3 up-to-date, 7 skipped ==========
```

**Comment by thewtex** [comment]
Great!

Does the *ElastixTargets.cmake* file have the `elastix_lib.lib` configuration, and does it set its path?

https://github.com/SuperElastix/elastix/blob/4b3ca0b27260e6ca4480a2edf074c6d32be1b8de/ElastixConfig.cmake.in#L15

Is *ElastixTarget.cmake* getting sourced in the configuration?

**Comment by dzenanz** [comment]
[ElastixTargets.cmake](https://github.com/InsightSoftwareConsortium/ITKElastix/files/5562651/ElastixTargets.zip) does have `elastix_lib` target and sets its path as so:
```CMake
# Import target "elastix_lib" for configuration "Debug"
set_property(TARGET elastix_lib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(elastix_lib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Dev/ITK-git-2015/lib/Debug/elastix-5.0.lib"
  )
```

_ElastixConfig.cmake_ has this line: `set( ELASTIX_CONFIG_TARGETS_FILE "${Elastix_DIR}/ElastixTargets.cmake" )`. Is _ElastixTargets.cmake_ supposed to be referenced by ITK? _C:\Dev\ITK-git-2015\lib\cmake\ITK-5.2\Modules\Elastix.cmake_ has this content:
```CMake
set(Elastix_LOADED 1)
set(Elastix_ENABLE_SHARED "0")
set(Elastix_DEPENDS "ITKCommon;ITKIOImageBase;ITKImageGrid;ITKImageSources;ITKSmoothing")
set(Elastix_PUBLIC_DEPENDS "ITKCommon;ITKIOImageBase;ITKImageGrid;ITKSmoothing")
set(Elastix_TRANSITIVE_DEPENDS "ITKCommon;ITKIOImageBase;ITKImageGrid;ITKImageSources;ITKSmoothing")
set(Elastix_PRIVATE_DEPENDS "")
set(Elastix_LIBRARIES "elastix_lib;transformix_lib")
set(Elastix_INCLUDE_DIRS "")
set(Elastix_LIBRARY_DIRS "")
set(Elastix_RUNTIME_LIBRARY_DIRS "C:/Dev/ITK-git-2015/bin")
set(Elastix_TARGETS_FILE "")
set(Elastix_FACTORY_NAMES "")

set(Elastix_DIR "C:/Dev/ITK-git-2015/_deps/elx-build")
find_package(Elastix REQUIRED)
```

**Comment by dzenanz** [comment]
If I manually change `set(Elastix_TARGETS_FILE "")` to `set(Elastix_TARGETS_FILE "C:/Dev/ITK-git-2015/_deps/elx-build/ElastixTargets.cmake")` the build of HASI succeeds.

**Comment by thewtex** [comment]
>  Is ElastixTargets.cmake supposed to be referenced by ITK?

Yes

The route should be:

1. ITK module configuration
2. C:\Dev\ITK-git-2015\lib\cmake\ITK-5.2\Modules\Elastix.cmake
3. find_package(Elastix REQUIRED)
4. ElastixConfig.cmake
5. ElastixTargets.cmake

> If I manually change set(Elastix_TARGETS_FILE "") to set(Elastix_TARGETS_FILE "C:/Dev/ITK-git-2015/_deps/elx-build/ElastixTargets.cmake") the build of HASI succeeds.

Can we patch *elastix/ElastixConfig.cmake.in* to address this?

**Comment by dzenanz** [comment]
My attempt https://github.com/dzenanz/ITKElastix/commit/9f218045eacddbc93418e3b01452ebcc72945e94 does not work. How would modifying `elastix/ElastixConfig.cmake.in` affect `C:\Dev\ITK-git-2015\lib\cmake\ITK-5.2\Modules\Elastix.cmake`?

**Comment by dzenanz** [comment]
Uncommenting https://github.com/InsightSoftwareConsortium/ITKElastix/blob/2f5987fe79dd9d76359eab1479b383a3bb7b8a8f/CMakeLists.txt#L64 causes CMake error in ITK:
```text
...
Enabled ITKZLIB, requested by ITK_BUILD_DEFAULT_MODULES.
CMake Error at C:/Dev/ITK-git-2015/_deps/elx-build/UseElastix.cmake:22 (include):
  The file

    C:/Dev/ITK-git-2015/_deps/elx-build/ElastixTargets.cmake

  was generated by the export() command.  It may not be used as the argument
  to the include() command.  Use ALIAS targets instead to refer to targets by
  alternative names.

Call Stack (most recent call first):
  Modules/Remote/Elastix/CMakeLists.txt:64 (include)


Checking for InitOnceExecuteOnce:
...
```

**Comment by thewtex** [comment]
> My attempt dzenanz@9f21804 does not work. How would modifying elastix/ElastixConfig.cmake.in affect C:\Dev\ITK-git-2015\lib\cmake\ITK-5.2\Modules\Elastix.cmake?

The change needs to be made in upstream `elastix`.

**Comment by dzenanz** [comment]
CMake Error at C:/Dev/ITK-git-2015/_deps/elx-build/ElastixConfig.cmake:19 (include):
  The file

    C:/Dev/ITK-git-2015/_deps/elx-build/ElastixTargets.cmake

  was generated by the export() command.  It may not be used as the argument
  to the include() command.  Use ALIAS targets instead to refer to targets by
  alternative names.

Call Stack (most recent call first):
  Modules/Remote/Elastix/CMakeLists.txt:61 (find_package)

**Comment by dzenanz** [comment]
https://stackoverflow.com/questions/37204734/correctly-set-cmake-variables-when-adding-yaml-cpp-to-existing-project

**Comment by dzenanz** [comment]
Update: we have a version of the involved software which compiles. I will follow up (this week or next) in respective repositories.

**Comment by thewtex** [comment]
Has this been addressed?

**Comment by dzenanz** [comment]
Partly addressed, partly abandoned.
